require 'csv'

# Define animal data
animals = [
{
  name: "Moose",
  scientific_name: "Alces alces",
  photo_url: "https://images.pexels.com/photos/76972/moose-moose-rack-male-bull-76972.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  description: "Moose are the largest members of the deer family, known for their large size, long legs, and broad antlers. They are commonly found in North America, Europe, and Asia.",
  top_speed: "35 mph",
  life_span: "15 years",
  weight: "1200 lbs",
  height: "6.5 ft",
  length: "10 ft",
  habitat: "Forests, wetlands, lakesides",
  predators: "gray wolves, mountain lions, black bears, coyotes",  
  prey: "grass",
  fun_fact: "Moose are excellent swimmers and can dive underwater to feed on aquatic plants.",
  animal_type: "mammal",
  diet: "Herbivore"
},  
  {
  name: "Black Bear",
  scientific_name: "Ursus americanus",
  photo_url: "https://images.pexels.com/photos/23914453/pexels-photo-23914453.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  top_speed: "30 mph",
  life_span: "25 years",
  weight: "300 lbs",
  height: "3 ft at shoulders",
  length: "6 ft",
  habitat: "Forests, Mountain Areas",
  predators: "mountain lions",
  prey: "ants, termites, rainbow trout, pika, yellow-bellied marmots, cottontail rabbits, bighorn sheep, mule deer, yellow-bellied marmots, coyotes, mountain goats, honeybees, bumblebees",
  fun_fact: "Black bears can climb trees with ease.",
  description: "Shy, omnivorous bear that avoids humans but loves berries and nuts.",
  animal_type: "mammal",
  diet: "Omnivore"
},
{
  name: "Elk",
  scientific_name: "Cervus canadensis",
  photo_url: "https://images.pexels.com/photos/29483733/pexels-photo-29483733.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  description: "Large members of the deer family, commonly seen grazing in the meadows of RMNP.",
  top_speed: "45 mph",
  life_span: "10 years",
  weight: "700 lbs",
  height: "4.5 ft",
  length: "8 ft",
  habitat: "Forests, meadows",
  predators: "mountain lions, black bears, gray wolves",
  prey: "grass",
  fun_fact: "Male elk are known for their bugling calls during the mating season.",
  animal_type: "mammal",
  diet: "Herbivore"
},
{
  name: "Bighorn Sheep",
  scientific_name: "Ovis canadensis",
  photo_url: "https://images.pexels.com/photos/12792487/pexels-photo-12792487.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  description: "Famous for their massive curved horns, often spotted on rugged mountain slopes.",
  top_speed: "30 mph",
  life_span: "15 years",
  weight: "200 lbs",
  height: "3 ft",
  length: "5 ft",
  habitat: "Rocky cliffs, mountain meadows",
  predators: "mountain lions, coyotes, golden eagles, black bears, gray wolves",
  prey: "grass",
  fun_fact: "Their horns can weigh up to 30 pounds, about the weight of a small child.",
  animal_type: "mammal",
  diet: "Herbivore"
},
  {
  name: "Mule Deer",
  scientific_name: "Odocoileus hemionus",
  photo_url: "https://images.pexels.com/photos/51390/elk-wildlife-nature-animal-51390.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  description: "Named for their large, mule-like ears, often seen at dawn or dusk.",
  top_speed: "35 mph",
  life_span: "9 years",
  weight: "200 lbs",
  height: "3.5 ft",
  length: "6 ft",
  habitat: "Open woodlands, shrublands",
  predators: "mountain lions, coyotes, black bears, bobcats, golden eagles, gray wolves",
  prey: "grass",
  fun_fact: "They bound with a unique hopping motion called stotting.",
  animal_type: "mammal",
  diet: "Herbivore"
},
{
  name: "Yellow-Bellied Marmot",
  scientific_name: "Marmota flaviventris",
  photo_url: "https://images.pexels.com/photos/12766489/pexels-photo-12766489.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  description: "A large ground squirrel often called the 'whistle pig' for its loud alarm calls.",
  top_speed: "10 mph",
  life_span: "15 years",
  weight: "12 lbs",
  height: "1 ft",
  length: "2 ft",
  habitat: "Alpine meadows, rocky outcrops",
  predators: "coyotes, red foxes, golden eagles, bobcats, black bears",
  prey: "grass",
  fun_fact: "They hibernate for up to 8 months of the year.",
  animal_type: "mammal",
  diet: "Herbivore"
},
{
  name: "Coyote",
  scientific_name: "Canis latrans",
  photo_url: "https://images.pexels.com/photos/15707992/pexels-photo-15707992.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  description: "A versatile canine known for its intelligence and adaptability.",
  top_speed: "43 mph",
  life_span: "10 years",
  weight: "30 lbs",
  height: "2 ft",
  length: "4.5 ft",
  habitat: "Grasslands, forests, mountains",
  predators: "mountain lions, gray wolves, black bears",
  prey: "bighorn sheep, mule deer, yellow-bellied marmots, cottontail rabbits, abert’s squirrels, pine squirrels, chipmunks, pikas, grasshoppers, bats, beavers, wyoming ground squirrel, turkey, porcupines, bobcats, mountain goats, red fox, Black-billed Magpie, Steller's Jays, Prairie Rattlesnakes",
  fun_fact: "Coyotes communicate using a variety of howls, yips, and barks.",
  animal_type: "mammal",
  diet: "Omnivore"
},
{
  name: "Beaver",
  scientific_name: "Castor canadensis",
  photo_url: "https://images.pexels.com/photos/12399354/pexels-photo-12399354.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  description: "A master architect of the animal kingdom, known for building dams and lodges.",
  top_speed: "6 mph",
  life_span: "12 years",
  weight: "60 lbs",
  height: "1.5 ft",
  length: "3 ft",
  habitat: "Streams, rivers, wetlands",
  predators: "mountain lions, gray wolves, black bears, coyotes, great-horned owls, golden eagles",
  prey: "trees, plants",
  fun_fact: "Their teeth never stop growing and are self-sharpening.",
  animal_type: "mammal",
  diet: "Herbivore"
},
{
  name: "Bat",
  scientific_name: "Chiroptera (Various species)",
  photo_url: "https://images.pexels.com/photos/2587639/pexels-photo-2587639.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  description: "The only mammals capable of sustained flight, with diverse species in RMNP.",
  top_speed: "60 mph",
  life_span: "20 years",
  weight: "0.5 lbs",
  height: "0.1 ft",
  length: "0.2 ft",
  habitat: "Caves, forests, rock crevices",
  predators: "great-horned owls, coyotes, red-tailed hawks, peregrine falcons, raccoons, bobcats, red fox",
  prey: "mosquitoes, snowberry clearwing moth",
  fun_fact: "Bats use echolocation to navigate and hunt in the dark.",
  animal_type: "mammal",
  diet: "Insectivore"
},
  {
    name: "Mountain Lion",
    scientific_name: "Puma concolor",
    photo_url: "https://images.pexels.com/photos/29070042/pexels-photo-29070042.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    description: "A stealthy predator also known as a cougar or puma.",
    top_speed: "50 mph",
    life_span: "12 years",
    weight: "140 lbs",
    height: "2.5 ft",
    length: "8 ft",
    habitat: "Mountain forests, deserts",
    predators: "none",
    prey: "bighorn sheep, mule deer, beavers, elk, coyotes, raccoons, cottontail rabbit, turkey, porcupines, wyoming ground squirrels, pine squirrels, abert’s squirrels, bobcats, mountain goats, red fox",
    fun_fact: "Mountain lions can leap as far as 40 feet in a single bound.",
    animal_type: "mammal",
    diet: "Carnivore"
  },
  {
    name: "Porcupine",
    scientific_name: "Erethizon dorsatum",
    photo_url: "https://images.pexels.com/photos/7723050/pexels-photo-7723050.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    description: "Slow-moving, nocturnal rodents known for their sharp quills and love of climbing trees.",
    top_speed: "2 mph",
    life_span: "5-7 years in the wild, up to 15 years in captivity",
    weight: "12-35 lbs",
    height: "1.5-2 ft",
    length: "2-3 ft",
    habitat: "Forests, rocky areas, and grasslands",
    predators: "mountain lions, bobcats, coyotes",
    prey: "plants",
    fun_fact: "Porcupines have about 30,000 quills that they use for defense.",
    animal_type: "mammal",
    diet: "Herbivore"
  },
  {
    name: "Pika",
    scientific_name: "Ochotona princeps",
    photo_url: "https://images.pexels.com/photos/10035016/pexels-photo-10035016.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    description: "Small, adorable mammals known for their high-pitched calls in rocky habitats.",
    top_speed: "15 mph",
    life_span: "7 years",
    weight: "0.4 lbs",
    height: "0.2 ft",
    length: "0.4 ft",
    habitat: "Rocky talus slopes",
    predators: "coyotes, bobcats, red foxes, golden eagles, red-tailed hawks",
    prey: "none",
    fun_fact: "They collect and store 'haystacks' of vegetation for winter survival.",
    animal_type: "mammal",
    diet: "Herbivore"
  },
  {
    name: "Cottontail Rabbit",
    scientific_name: "Sylvilagus nuttallii",
    photo_url: "https://images.pexels.com/photos/18094514/pexels-photo-18094514.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    description: "A small rabbit with a distinctive white tail, commonly found in open habitats.",
    top_speed: "18 mph",
    life_span: "3 years",
    weight: "2.5 lbs",
    height: "1.2 ft",
    length: "14 in",
    habitat: "Grasslands, shrubs, and lowland forests",
    predators: "coyotes, red foxes, great-horned owls, mountain lions, bobcats, red-tailed hawks, golden eagles, bald eagles, red fox, Prairie Rattlesnake",
    prey: "grass",
    fun_fact: "Mountain Cottontails often use their tail to signal alarm when danger approaches.",
    animal_type: "mammal",
    diet: "Herbivore"
  },
  {
    name: "Gray Wolf",
    scientific_name: "Canis lupus",
    photo_url: "https://images.pexels.com/photos/27067812/pexels-photo-27067812.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    description: "An iconic predator known for its pack behavior and howling.",
    top_speed: "37 mph",
    life_span: "13 years",
    weight: "100 lbs",
    height: "2.5 ft",
    length: "5 ft",
    habitat: "Forests, tundras, grasslands",
    predators: "none",
    prey: "beavers, moose, coyote, red fox, elk, mule deer, bighorn sheep, mountain goats",
    fun_fact: "Gray wolves have a complex social structure within their packs.",
    animal_type: "mammal",
    diet: "Carnivore"
  },
  {
    name: "Bobcat",
    scientific_name: "Lynx rufus",
    photo_url: "https://images.pexels.com/photos/11533125/pexels-photo-11533125.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    description: "A medium-sized wildcat with a short 'bobbed' tail, tufted ears, and a spotted coat, known for its adaptability and stealth.",
    top_speed: "30 mph",
    life_span: "7 years",
    weight: "20 lbs",
    height: "2 ft",
    length: "3 ft",
    habitat: "Forests, deserts, swamps, and suburban areas",
    predators: "mountain lions, coyotes",
    prey: "mule deer, yellow-bellied marmots, bats, turkey, porcupines, pika, cottontail rabbits, abert’s squirrels, pine squirrels, mountain goats",
    fun_fact: "Bobcats are solitary animals and use scent marking and vocalizations to define their territory.",
    animal_type: "mammal",
    diet: "Carnivore"
  },
  {
    name: "Mountain Goat",
    scientific_name: "Oreamnos americanus",
    photo_url: "https://images.pexels.com/photos/29435674/pexels-photo-29435674.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    description: "Sure-footed climbers often found on steep, rocky slopes.",
    top_speed: "15 mph",
    life_span: "9 years",
    weight: "200 lbs",
    height: "3 ft",
    length: "5 ft",
    habitat: "Alpine, cliffs",
    predators: "mountain lions, coyotes, golden eagles, gray wolves, black bears, bobcats",
    prey: "grass",
    fun_fact: "Mountain goats' hooves have a rough texture for gripping rocks.",
    animal_type: "mammal",
    diet: "Herbivore"
  },
  {
    name: "Abert's Squirrel",
    scientific_name: "Sciurus aberti",
    photo_url: "https://images.pexels.com/photos/8365761/pexels-photo-8365761.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    description: "A tree squirrel distinguished by its long ear tufts.",
    top_speed: "12 mph",
    life_span: "7 years",
    weight: "1.5 lbs",
    height: "0.5 ft",
    length: "1.5 ft",
    habitat: "Ponderosa pine forests",
    predators: "coyotes, mountain lions, bobcats, bald eagles",
    prey: "grass",
    fun_fact: "Abert's squirrels depend on ponderosa pine for both food and shelter.",
    animal_type: "mammal",
    diet: "Herbivore"
  },
  {
    name: "Pine Squirrel",
    scientific_name: "Tamiasciurus hudsonicus",
    photo_url: "https://images.pexels.com/photos/1571117/pexels-photo-1571117.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    description: "A small, vocal squirrel known for its chattering calls.",
    top_speed: "15 mph",
    life_span: "8 years",
    weight: "0.7 lbs",
    height: "0.3 ft",
    length: "1.2 ft",
    habitat: "Coniferous forests",
    predators: "coyotes, mountain lions, bobcats, bald eagles",
    prey: "grass",
    fun_fact: "Pine squirrels stash cones in large caches for winter survival.",
    animal_type: "mammal",
    diet: "Omnivore"
  },
  {
    name: "Wyoming Ground Squirrel",
    scientific_name: "Urocitellus elegans",
    photo_url: "https://images.pexels.com/photos/3635178/pexels-photo-3635178.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    description: "A burrowing rodent commonly seen in open grasslands.",
    top_speed: "10 mph",
    life_span: "5 years",
    weight: "1.5 lbs",
    height: "0.4 ft",
    length: "0.8 ft",
    habitat: "Grasslands, sagebrush",
    predators: "coyotes, mountain lion, red-tailed hawks, Prairie Rattlesnake",
    prey: "grass",
    fun_fact: "These squirrels hibernate for up to six months a year.",
    animal_type: "mammal",
    diet: "Herbivore"
  },
  {
    name: "Chipmunk",
    scientific_name: "Tamias minimus",
    photo_url: "https://images.pexels.com/photos/681178/pexels-photo-681178.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    description: "The smallest chipmunk species in North America.",
    top_speed: "10 mph",
    life_span: "3 years",
    weight: "0.1 lbs",
    height: "0.3 ft",
    length: "0.6 ft",
    habitat: "Forests, grasslands, rocky areas",
    predators: "coyotes, red-tailed hawks, great-horned owls, garter snakes",
    prey: "grass",
    fun_fact: "They can gather food equal to their body weight in a single day.",
    animal_type: "mammal",
    diet: "Omnivore"
  },
  {
    name: "Red Fox",
    scientific_name: "Vulpes vulpes",
    photo_url: "https://images.pexels.com/photos/158340/fuchs-wild-animal-predator-animal-world-158340.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    top_speed: "31 mph",
    life_span: "2-5 years in the wild, up to 14 years in captivity",
    weight: "10-15 lbs",
    height: "1.5 ft",
    length: "3 ft",
    habitat: "Forests, grasslands, mountains, suburban areas",
    predators: "Coyotes, gray wolves, mountain lions",
    prey: "Cottontail rabbits, yellow-bellied marmots, bats, turkeys, pika, Mountain Chickadees, Western Painted Turtle",
    fun_fact: "Red foxes use their bushy tails for balance and as a warm cover in cold weather.",
    description: "Adaptable mammals with reddish fur, known for their cunning behavior and diverse diet.",
    animal_type: "mammal",
    diet: "Omnivore"
  },
  {
    name: "Raccoon",
    scientific_name: "Procyon lotor",
    photo_url: "https://images.pexels.com/photos/16605/pexels-photo.jpg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    top_speed: "15 mph",
    life_span: "2-5 years in the wild, up to 20 years in captivity",
    weight: "10-20 lbs",
    height: "1.5 ft",
    length: "2.5 ft",
    habitat: "Forests, wetlands, urban areas",
    predators: "Coyotes, bobcats, mountain lions, great horned owls",
    prey: "bats, Western Fence Lizard, Garter Snakes, Western Painted Turtle, Northern Leopard Frogs, Tiger Salamanders, honeybees, bumblebees, Black Widow Spiders, Deer Ticks, Crayfish",
    fun_fact: "Raccoons are known for their dexterous front paws, which allow them to manipulate objects and open containers.",
    description: "Nocturnal mammals with a distinctive mask-like facial pattern and a bushy, ringed tail, known for their intelligence and adaptability.",
    animal_type: "mammal",
    diet: "Omnivore"
  },
  {
    name: "Bald Eagle",
    scientific_name: "Haliaeetus leucocephalus",
    photo_url: "https://images.pexels.com/photos/3250638/pexels-photo-3250638.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    description: "A majestic bird of prey with a white head and tail, symbolizing the United States.",
    top_speed: "75 mph",
    life_span: "28 years",
    weight: "22 lbs",
    height: "3 ft",
    length: "3.5 ft",
    habitat: "Lakes, rivers, forests",
    predators: "golden eagles",
    prey: "cottontail rabbits, abert’s squirrels, pine squirrels, rainbow trout, Osprey",
    fun_fact: "Bald eagles build the largest nests of any bird in North America.",
    animal_type: "bird",
    diet: "Carnivore"
  },
  {
    name: "Golden Eagle",
    scientific_name: "Aquila chrysaetos",
    photo_url: "https://images.pexels.com/photos/2846072/pexels-photo-2846072.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    description: "A large raptor with golden feathers on its nape and a powerful build.",
    top_speed: "200 mph",
    life_span: "30 years",
    weight: "33 lbs",
    height: "3 ft",
    length: "3.5 ft",
    habitat: "Mountains, grasslands, cliffs",
    predators: "none",
    prey: "bighorn sheep, mule deer, yellow-bellied marmots, beavers, pika, cottontail rabbits, mountain goats, red-tailed hawks, Peregrine Falcons, Osprey, Black-billed Magpie, Steller's Jays, Mountain Bluebirds",
    fun_fact: "Golden eagles can spot prey from more than two miles away.",
    animal_type: "bird",
    diet: "Carnivore"
  },
  {
    name: "Red-Tailed Hawk",
    scientific_name: "Buteo jamaicensis",
    photo_url: "https://images.pexels.com/photos/3954869/pexels-photo-3954869.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    description: "A common hawk with a reddish tail and a piercing call often used in movies.",
    top_speed: "120 mph",
    life_span: "20 years",
    weight: "6.6 lbs",
    height: "2 ft",
    length: "2.3 ft",
    habitat: "Grasslands, forests, deserts",
    predators: "golden eagles, great-horned owls",
    prey: "pika, bats, cottontail rabbits, Wyoming Ground Squirrels, Chipmunk, Black-billed Magpies, Steller's Jays, Mountain Bluebirds, Gray Jays, western fence lizards, Prairie Rattlesnakes, Garter Snakes",
    fun_fact: "They are monogamous and may stay with the same mate for life.",
    animal_type: "bird",
    diet: "Carnivore"
  },
  {
    name: "Peregrine Falcon",
    scientific_name: "Falco peregrinus",
    photo_url: "https://images.pexels.com/photos/2548433/pexels-photo-2548433.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    description: "The fastest bird in the world, capable of diving at incredible speeds.",
    top_speed: "240 mph",
    life_span: "15 years",
    weight: "4.4 lbs",
    height: "1.5 ft",
    length: "1.5 ft",
    habitat: "Cliffs, forests, urban areas",
    predators: "golden eagles, great-horned owls",
    prey: "bats, mountain bluebird, whitecrowned sparrows, mountain chickadees",
    fun_fact: "Peregrine falcons have been clocked diving at over 240 mph.",
    animal_type: "bird",
    diet: "Carnivore"
  },
  {
    name: "Osprey",
    scientific_name: "Pandion haliaetus",
    photo_url: "https://images.pexels.com/photos/7014688/pexels-photo-7014688.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    description: "A fish-eating raptor with a distinct M-shaped flight pattern.",
    top_speed: "50 mph",
    life_span: "25 years",
    weight: "8.8 lbs",
    height: "2 ft",
    length: "2.1 ft",
    habitat: "Lakes, rivers, coasts",
    predators: "golden eagles, bald eagles",
    prey: "rainbow trout",
    fun_fact: "Ospreys have reversible outer toes to help them grasp fish.",
    animal_type: "bird",
    diet: "Carnivore"
  },
  {
    name: "Great Horned Owl",
    scientific_name: "Bubo virginianus",
    photo_url: "https://images.pexels.com/photos/1980867/pexels-photo-1980867.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    description: "A large owl with prominent ear tufts and piercing yellow eyes.",
    top_speed: "40 mph",
    life_span: "13 years",
    weight: "7.05 lbs",
    height: "2.1 ft",
    length: "2.3 ft",
    habitat: "Forests, grasslands, urban areas",
    predators: "golden eagles, bald eagles",
    prey: "beavers, cottontail rabbits, Chipmunk, red-tailed hawks, Peregrine Falcons, prairie rattlesnakes, Gray Jays, Mountain Chickadees, Garter Snakes",
    fun_fact: "Great horned owls are known as the 'tiger of the sky' for their ferocity.",
    animal_type: "bird",
    diet: "Carnivore"
  },
  {
    name: "Wild Turkey",
    scientific_name: "Meleagris gallopavo",
    photo_url: "https://images.pexels.com/photos/12043816/pexels-photo-12043816.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    description: "Large ground-dwelling birds with iridescent feathers and a distinctive gobble.",
    top_speed: "20 mph on ground, 55 mph in flight",
    life_span: "3-5 years in the wild, up to 10 years in captivity",
    weight: "8-24 lbs",
    height: "3-4 ft",
    length: "4-4.5 ft (with tail)",
    habitat: "Forests, meadows, and grasslands",
    predators: "Coyotes, bobcats, mountain lions, red foxes",
    prey: "None",
    fun_fact: "Male turkeys, called toms, can puff out their feathers, fan their tails, and gobble loudly to attract mates.",
    animal_type: "bird",
    diet: "Omnivore"
  },
  {
    name: "Black-billed Magpie",
    scientific_name: "Pica hudsonia",
    photo_url: "https://images.pexels.com/photos/4168320/pexels-photo-4168320.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    description: "A striking black-and-white bird with iridescent blue-green feathers on its wings and tail.",
    top_speed: "20 mph",
    life_span: "6 years",
    weight: "0.44 lbs",
    height: "0.5 ft",
    length: "0.45 ft",
    habitat: "Open woodlands, grasslands, and near human settlements",
    predators: "red-tailed hawks, golden eagles, coyotes",
    prey: "grasshoppers, deer ticks",
    fun_fact: "Black-billed magpies are highly intelligent and known for their social behavior and vocalizations.",
    animal_type: "bird",
    diet: "Omnivore"
  },
  {
    name: "Steller's Jay",
    scientific_name: "Cyanocitta stelleri",
    photo_url: "https://images.pexels.com/photos/3379017/pexels-photo-3379017.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    description: "A bold bird with striking blue feathers and a black crested head, often found in mountainous forests.",
    top_speed: "30 mph",
    life_span: "8 years",
    weight: "0.33 lbs",
    height: "0.4 ft",
    length: "0.34 ft",
    habitat: "Coniferous forests, montane woodlands",
    predators: "red-tailed hawks, golden eagles, coyotes, garter snakes",
    prey: "grasshoppers",
    fun_fact: "Steller's jays are known for mimicking the calls of other birds and even mammals.",
    animal_type: "bird",
    diet: "Omnivore"
  },
  {
    name: "Mountain Bluebird",
    scientific_name: "Sialia currucoides",
    photo_url: "https://images.pexels.com/photos/12489562/pexels-photo-12489562.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    description: "A small, vibrant blue bird found in mountainous areas, known for its bright blue plumage.",
    top_speed: "25 mph",
    life_span: "6 years",
    weight: "0.055 lbs",
    height: "0.3 ft",
    length: "0.22 ft",
    habitat: "Open meadows, high-altitude forests, grasslands",
    predators: "Peregrine Falcons, red-tailed hawks, golden eagles",
    prey: "grasshoppers, ants, termites, Snowberry Clearwing Moth",
    fun_fact: "Mountain bluebirds are known for their aerial acrobatics while catching insects.",
    animal_type: "bird",
    diet: "Insectivore"
  },
  {
    name: "Gray Jay",
    scientific_name: "Perisoreus canadensis",
    photo_url: "https://images.pexels.com/photos/5673015/pexels-photo-5673015.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    description: "A medium-sized bird with soft gray plumage and a pale face, often seen in high-elevation coniferous forests.",
    top_speed: "25 mph",
    life_span: "10 years",
    weight: "0.18 lbs",
    height: "0.3 ft",
    length: "0.27 ft",
    habitat: "Boreal forests, subalpine zones",
    predators: "red-tailed hawks, great horned owls",
    prey: "grasshoppers, ants, termites, Snowberry Clearwing Moth",
    fun_fact: "Gray jays are known as 'camp robbers' for their bold habit of stealing food from campers and hikers.",
    animal_type: "bird",
    diet: "Omnivore"
  },
  {
    name: "Mountain Chickadee",
    scientific_name: "Poecile gambeli",
    photo_url: "https://images.pexels.com/photos/29484241/pexels-photo-29484241.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    description: "A small, curious bird with a black cap and white cheeks, often found in coniferous forests.",
    top_speed: "18 mph",
    life_span: "7 years",
    weight: "0.04 lbs",
    height: "0.15 ft",
    length: "0.12 ft",
    habitat: "High-altitude forests, coniferous woodlands",
    predators: "Peregrine Falcons, great-horned owls, red foxes",
    prey: "grasshoppers, ants, termites, Snowberry Clearwing Moth, Two-tailed Swallowtail, Cabbage White, Black Swallowtail, painted lady, Deer Ticks",
    fun_fact: "Mountain chickadees are known for their distinctive 'chick-a-dee-dee' call.",
    animal_type: "bird",
    diet: "Omnivore"
  },
  {
    name: "Western Fence Lizard",
    scientific_name: "Sceloporus occidentalis",
    photo_url: "https://images.pexels.com/photos/2555199/pexels-photo-2555199.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    description: "A common lizard with blue markings on its belly, often seen basking on rocks.",
    top_speed: "8 mph",
    life_span: "5 years",
    weight: "0.11 lbs",
    height: "0.1 ft",
    length: "0.25 ft",
    habitat: "Rocky outcrops, woodlands, scrublands",
    predators: "raccoons, garter snakes, red-tailed hawks",
    prey: "ants, termites, grasshoppers, black-widow spiders, brown recluse spiders, funnel web spiders",
    fun_fact: "Western fence lizards can perform push-ups as part of their territorial displays.",
    animal_type: "reptile",
    diet: "Insectivore"
  },
  {
    name: "Prairie Rattlesnake",
    scientific_name: "Crotalus viridis",
    photo_url: "https://images.pexels.com/photos/2618894/pexels-photo-2618894.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    description: "A venomous snake with distinctive rattles at the end of its tail, found in open grasslands and rocky hills.",
    top_speed: "3 mph",
    life_span: "20 years",
    weight: "3.31 lbs",
    height: "0.1 ft",
    length: "1.5 ft",
    habitat: "Grasslands, rocky outcrops",
    predators: "Great Horned Owls, coyotes, red-tailed hawks",
    prey: "wyoming ground squirrels, cottontail rabbits",
    fun_fact: "Northern prairie rattlesnakes use their rattles to warn predators and humans of their presence.",
    animal_type: "reptile",
    diet: "Carnivore"
  },
  {
    name: "Garter Snake",
    scientific_name: "Thamnophis sirtalis",
    photo_url: "https://images.pexels.com/photos/162347/snake-young-animal-cute-slim-162347.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    description: "A slender, green or brown snake with longitudinal stripes, often found in moist areas.",
    top_speed: "3 mph",
    life_span: "6 years",
    weight: "0.22 lbs",
    height: "0.1 ft",
    length: "0.7 ft",
    habitat: "Wetlands, grasslands, forests",
    predators: "red-tailed hawks, great horned owls, raccoons",
    prey: "Chipmunks, Western Fence Lizard, grasshoppers, Northern Leopard Frogs, Tiger Salamanders",
    fun_fact: "Common garter snakes often eat amphibians, small fish, and earthworms.",
    animal_type: "reptile",
    diet: "Carnivore"
  },
  {
    name: "Western Painted Turtle",
    scientific_name: "Chrysemys picta belli",
    photo_url: "https://images.pexels.com/photos/3387169/pexels-photo-3387169.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    description: "A freshwater turtle with striking red and yellow markings on its shell and skin.",
    top_speed: "0.5 mph",
    life_span: "50 years",
    weight: "2.2 lbs",
    height: "0.2 ft",
    length: "0.3 ft",
    habitat: "Ponds, lakes, marshes",
    predators: "raccoons, red foxes",
    prey: "water striders, rainbow trout, crayfish",
    fun_fact: "Western painted turtles are known for basking on logs or rocks during warm weather.",
    animal_type: "reptile",
    diet: "Omnivore"
  },
  {
    name: "Northern Leopard Frog",
    scientific_name: "Rana pipiens",
    photo_url: "https://images.pexels.com/photos/27986855/pexels-photo-27986855.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    description: "A large frog with distinctive dark spots, often found near permanent water bodies.",
    top_speed: "5 mph",
    life_span: "8 years",
    weight: "0.13 lbs",
    height: "0.05 ft",
    length: "0.1 ft",
    habitat: "Lakes, ponds, marshes",
    predators: "garter snakes, raccoons",
    prey: "grasshoppers, water striders, blue dasher dragonflies, ruddy darter dragonflies, mayflies, brown recluse spiders",
    fun_fact: "Northern leopard frogs have a distinct leopard-like pattern, making them easily recognizable.",
    animal_type: "amphibian",
    diet: "Insectivore"
  },
  {
    name: "Tiger Salamander",
    scientific_name: "Ambystoma tigrinum",
    photo_url: "https://images.pexels.com/photos/4238608/pexels-photo-4238608.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    description: "A large salamander known for its yellow or orange tiger-like markings.",
    top_speed: "2 mph",
    life_span: "20 years",
    weight: "0.44 lbs",
    height: "0.05 ft",
    length: "0.3 ft",
    habitat: "Woodlands, grasslands, ponds",
    predators: "garter snakes, raccoons",
    prey: "grasshoppers, funnel web spiders",
    fun_fact: "Tiger salamanders are one of the largest terrestrial salamanders in North America.",
    animal_type: "amphibian",
    diet: "Carnivore"
  },
  {
    name: "Rainbow Trout",
    scientific_name: "Oncorhynchus mykiss",
    photo_url: "https://images.pexels.com/photos/3311091/pexels-photo-3311091.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    description: "A brightly colored trout with a characteristic rainbow stripe along its side, native to cold water environments.",
    top_speed: "6 mph",
    life_span: "6 years",
    weight: "4.41 lbs",
    height: "0.2 ft",
    length: "0.5 ft",
    habitat: "Streams, rivers, lakes",
    predators: "bald eagles, osprey, Western Painted Turtle",
    prey: "mayflies, crawfish, ruddy darter dragonfly, blue dasher dragonfly",
    fun_fact: "Rainbow trout are popular among anglers due to their fighting ability when hooked.",
    animal_type: "fish",
    diet: "Omnivore"
  },
  {
    name: "Mayfly",
    scientific_name: "Ephemeroptera",
    photo_url: "https://images.pexels.com/photos/9496097/pexels-photo-9496097.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    description: "Mayflies are aquatic insects known for their brief adult lifespan, typically only lasting a day or two. They are an important food source for many animals.",
    top_speed: "1 mph",
    life_span: "1 day",
    weight: "0.00022 lbs",
    height: "0.01 ft",
    length: "0.03 ft",
    habitat: "Freshwater bodies, such as streams, rivers, and lakes",
    predators: "rainbow trout, northern leopard frogs, blue dasher dragonflies, ruddy darter dragonflies, Crayfish",
    prey: "plants",
    fun_fact: "Mayflies are known for their short adult lifespan, with some species living only for a few hours.",
    animal_type: "Insect",
    diet: "Detritivore (as nymphs), some species feed on nectar (as adults)"
  },
  {
    name: "Painted Lady",
    scientific_name: "Vanessa cardui",
    photo_url: "https://images.pexels.com/photos/633437/pexels-photo-633437.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    description: "A common butterfly with orange and black patterns, known for migrating long distances.",
    top_speed: "6 mph",
    life_span: "1 year",
    weight: "0.0066 lbs",
    height: "0.03 ft",
    length: "0.05 ft",
    habitat: "Open fields, gardens, meadows",
    predators: "funnel web spiders, black widow spiders, mountain chickadees, ants",
    prey: "nectar",
    fun_fact: "Painted Lady butterflies are one of the most widespread butterfly species in the world.",
    animal_type: "insect",
    diet: "Nectar from flowers"
  },
  {
    name: "Black Swallowtail",
    scientific_name: "Papilio polyxenes",
    photo_url: "https://images.pexels.com/photos/8921055/pexels-photo-8921055.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    description: "A striking butterfly with black wings adorned by yellow spots and blue bands, common in North America.",
    top_speed: "15 mph",
    life_span: "1 year",
    weight: "1.32 lbs",
    height: "0.02 ft",
    length: "0.1 ft",
    habitat: "Meadows, gardens, and forest edges",
    predators: "funnel web spiders, black widow spiders, mountain chickadees, ants",
    prey: "",
    fun_fact: "Black Swallowtail caterpillars resemble bird droppings in their early stages to deter predators.",
    animal_type: "insect",
    diet: "Nectar from thistles, clovers, and milkweed"
  },
  {
    name: "Cabbage White",
    scientific_name: "Pieris rapae",
    photo_url: "https://images.pexels.com/photos/1246966/pexels-photo-1246966.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    description: "A small, pale butterfly with white wings marked by black spots, commonly seen fluttering in gardens.",
    top_speed: "10 mph",
    life_span: "1 year",
    weight: "0.44 lbs",
    height: "0.015 ft",
    length: "0.07 ft",
    habitat: "Gardens, fields, and urban areas",
    predators: "funnel web spiders, black widow spiders, mountain chickadees, ants",
    prey: "",
    fun_fact: "Cabbage White butterflies are a major pest for cruciferous crops, but their caterpillars are a favorite of birds.",
    animal_type: "insect",
    diet: "Nectar from clover, dandelions, and mustard plants"
  },
  {
    name: "Two-tailed Swallowtail",
    scientific_name: "Papilio multicaudata",
    photo_url: "https://images.pexels.com/photos/67811/butterfly-swallowtail-papilio-animal-67811.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    description: "A large, yellow butterfly with black tiger stripes and two distinctive tails on each hindwing, often found in the western United States.",
    top_speed: "15 mph",
    life_span: "1 year",
    weight: "1.32 lbs",
    height: "0.02 ft",
    length: "0.12 ft",
    habitat: "Canyons, deserts, woodlands, and suburban areas",
    predators: "funnel web spiders, black widow spiders, mountain chickadees, ants",
    prey: "",
    fun_fact: "The Two-tailed Swallowtail is the state butterfly of Arizona and can often be seen soaring high in canyons.",
    animal_type: "insect",
    diet: "Nectar from flowers such as lilac, thistle, and milkweed"
  },
  {
    name: "Grasshopper",
    scientific_name: "Caelifera",
    photo_url: "https://images.pexels.com/photos/289417/pexels-photo-289417.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    description: "A small to medium-sized insect known for its powerful hind legs, which allow it to leap great distances.",
    top_speed: "8 mph",
    life_span: "1 year",
    weight: "0.0044 lbs",
    height: "0.03 ft",
    length: "0.05 ft",
    habitat: "Grasslands, meadows, forests, and agricultural fields",
    predators: "coyotes, Black-billed Magpies, Steller's Jays, Mountain Bluebirds, Gray Jays, Mountain Chickadees, Western Fence Lizards, Garter Snake, Northern Leopard Frogs, Tiger Salamanders, Brown Recluse Spiders",
    prey: "grass",
    fun_fact: "Grasshoppers communicate with each other by making chirping sounds through a process called stridulation, rubbing their wings or legs together.",
    animal_type: "insect",
    diet: "Herbivore, primarily feeding on grasses and leaves"
  },
  {
    name: "Bumblebee",
    scientific_name: "Bombus balteatus",
    photo_url: "https://images.pexels.com/photos/553251/pexels-photo-553251.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    description: "A large, fuzzy bee commonly found in alpine meadows, known for its industrious pollination habits.",
    top_speed: "10 mph",
    life_span: "1 year",
    weight: "0.044 lbs",
    height: "0.01 ft",
    length: "0.02 ft",
    habitat: "Alpine meadows and wildflower fields",
    predators: "black bears, raccoons",
    prey: "nectar",
    fun_fact: "Mountain Bumblebees are vital pollinators for many high-altitude plants.",
    animal_type: "insect",
    diet: "Nectar and pollen from wildflowers"
  },
  {
    name: "Honeybee",
    scientific_name: "Apis mellifera",
    photo_url: "https://images.pexels.com/photos/460961/pexels-photo-460961.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    description: "The well-known, industrious bee, often seen in gardens and orchards, recognized for its honey production.",
    top_speed: "15 mph",
    life_span: "1 year",
    weight: "0.015 lbs",
    height: "0.01 ft",
    length: "0.02 ft",
    habitat: "Gardens, orchards, meadows",
    predators: "black bears, raccoons",
    prey: "nectar",
    fun_fact: "Western Honeybees are essential for pollinating many of the world's food crops.",
    animal_type: "insect",
    diet: "Nectar and pollen"
  },
  {
    name: "Blue Dasher Dragonfly",
    scientific_name: "Pachydiplax longipennis",
    photo_url: "https://images.pexels.com/photos/26867371/pexels-photo-26867371.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    description: "A small, brightly colored dragonfly with blue markings, typically found in marshy areas.",
    top_speed: "15 mph",
    life_span: "1 year",
    weight: "0.008 lbs",
    height: "0.015 ft",
    length: "0.04 ft",
    habitat: "Wetlands, ponds, marshes",
    predators: "Northern Leopard Frogs, rainbow trout",
    prey: "mayflies, mosquitoes",
    fun_fact: "The Blue Dasher is known for its darting flight style as it hunts for prey.",
    animal_type: "insect",
    diet: "Small flying insects like mosquitoes and flies"
  },
  {
    name: "Ruddy Darter Dragonfly",
    scientific_name: "Sympetrum sanguineum",
    photo_url: "https://images.pexels.com/photos/17818750/pexels-photo-17818750.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    description: "A vibrant dragonfly with red and black coloring, commonly seen near shallow ponds.",
    top_speed: "20 mph",
    life_span: "1 year",
    weight: "0.01 lbs",
    height: "0.02 ft",
    length: "0.05 ft",
    habitat: "Ponds, lakes, wetlands",
    predators: "Northern Leopard Frogs, rainbow trout",
    prey: "mayflies, mosquitoes",
    fun_fact: "Ruddy Darters are often found perching on low vegetation near water.",
    animal_type: "insect",
    diet: "Small insects, especially mosquitoes"
  },
  {
    name: "Mosquito",
    scientific_name: "Culicidae",
    photo_url: "https://images.pexels.com/photos/1149668/pexels-photo-1149668.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    description: "Small, slender-bodied insects with long legs and a proboscis used for feeding, often found in areas with stagnant water.",
    top_speed: "1.5 mph",
    life_span: "7 days",
    weight: "0.000002 lbs",
    height: "0.004 ft",
    length: "0.006 ft",
    habitat: "Wetlands, marshes, forests, and urban areas with standing water",
    predators: "bats, Ruddy Darter Dragonfly, Blue Dasher Dragonfly, Water Strider",
    prey: "blood, nectar",
    fun_fact: "Only female mosquitoes bite and consume blood to develop their eggs, while males primarily feed on nectar.",
    animal_type: "insect",
    diet: "Nectar, plant juices; females also consume blood for reproduction"
  },
  {
    name: "Water Strider",
    scientific_name: "Gerridae",
    photo_url: "https://images.pexels.com/photos/10460/pexels-photo-10460.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    description: "Slender, long-legged insects that skim effortlessly across the surface of ponds and streams.",
    top_speed: "1.5 mph",
    life_span: "6 months",
    weight: "0.002 lbs",
    height: "0.008 ft",
    length: "0.012 ft",
    habitat: "Ponds, streams, and calm water bodies",
    predators: "Western Painted Turtles, Northern Leopard Frogs",
    prey: "mosquitoes",
    fun_fact: "Water striders can walk on water thanks to specialized water-repellent hairs on their legs.",
    animal_type: "insect",
    diet: "Small insects and larvae trapped on the water's surface"
  },
  {
    name: "Ant",
    scientific_name: "Formicidae",
    photo_url: "https://images.pexels.com/photos/1104974/pexels-photo-1104974.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    description: "Social insects that live in large colonies, with specialized roles for workers, soldiers, and queens.",
    top_speed: "0.3 mph",
    life_span: "Several weeks to years depending on species",
    weight: "0.00003 lbs",
    height: "0.003 ft",
    length: "0.01 ft",
    habitat: "Forests, meadows, underground colonies",
    predators: "bears, Mountain Bluebirds, Gray Jays, Mountain Chickadees, western fence lizards, Brown Recluse Spiders",
    prey: "Two-tailed Swallowtail, Cabbage White, Black Swallowtail, painted lady, Black Widow Spiders",
    fun_fact: "Ants can carry objects 10-50 times their body weight.",
    animal_type: "insect",
    diet: "Omnivore"
  },
  {
    name: "Termite",
    scientific_name: "Isoptera",
    photo_url: "https://images.pexels.com/photos/12895294/pexels-photo-12895294.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    top_speed: "0.2 mph",
    life_span: "1-2 years (workers); up to 20 years (queen)",
    weight: "0.00003 lbs",
    height: "0.002 ft",
    length: "0.01 ft",
    habitat: "Dead wood, soil, underground colonies",
    predators: "Mountain Bluebird, Gray Jays, Mountain Chickadee, western fence lizards",
    prey: "wood",
    fun_fact: "Termites are vital decomposers, recycling nutrients in ecosystems.",
    description: "Small, eusocial insects known for their wood-consuming behavior and significant ecological impact.",
    animal_type: "insect",
    diet: "Herbivore"
  },
  {
    name: "Snowberry Clearwing Moth",
    scientific_name: "Hemaris diffinis",
    photo_url: "https://example.com/snowberry_clearwing_moth.jpg",
    description: "A moth resembling a hummingbird with transparent wings, often found around flowering shrubs, particularly snowberries.",
    top_speed: "15 mph",
    life_span: "1 year",
    weight: "0.002 lbs",
    height: "0.05 ft",
    length: "0.02 ft",
    habitat: "Meadows, gardens, forest edges",
    predators: "bats, mountain bluebird, Gray Jays, Mountain Chickadees",
    prey: "nectar",
    fun_fact: "This moth's flight resembles a hummingbird's, with rapid wing beats allowing it to hover while feeding on nectar.",
    animal_type: "insect",
    diet: "Nectar from flowering plants"
  },
  {
    name: "Black Widow Spider",
    scientific_name: "Latrodectus mactans",
    photo_url: "https://images.pexels.com/photos/16326004/pexels-photo-16326004.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    description: "A venomous spider with a distinctive red hourglass marking on its abdomen.",
    top_speed: "3 mph",
    life_span: "3 years",
    weight: "0.002 lbs",
    height: "0.03 ft",
    length: "0.05 ft",
    habitat: "Dark, secluded areas such as sheds, basements, and woodpiles",
    predators: "western fence lizards, raccoons, ants",
    prey: "Two-tailed Swallowtail, Cabbage White, Black Swallowtail, painted lady",
    fun_fact: "Black Widow Spiders are known for their potent venom, but bites are rarely fatal to humans.",
    animal_type: "arachnid",
    diet: "Insects"
  },
  {
    name: "Brown Recluse Spider",
    scientific_name: "Loxosceles reclusa",
    photo_url: "https://images.pexels.com/photos/26588223/pexels-photo-26588223.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    description: "A venomous spider with a violin-shaped mark on its back, often found in undisturbed areas.",
    top_speed: "3 mph",
    life_span: "2 years",
    weight: "0.002 lbs",
    height: "0.03 ft",
    length: "0.05 ft",
    habitat: "Woodpiles, basements, attics, closets",
    predators: "western fence lizards, northern leopard frogs",
    prey: "grasshoppers, ants",
    fun_fact: "Brown Recluse Spiders are reclusive and only bite in self-defense.",
    animal_type: "arachnid",
    diet: "Insects"
  },
  {
    name: "Funnel Web Spider",
    scientific_name: "Agelenidae",
    photo_url: "https://images.pexels.com/photos/3761419/pexels-photo-3761419.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    description: "A spider that spins a funnel-shaped web, often found in grassy areas.",
    top_speed: "2 mph",
    life_span: "1 year",
    weight: "0.003 lbs",
    height: "0.03 ft",
    length: "0.06 ft",
    habitat: "Grassy areas, forests, and gardens",
    predators: "western fence lizards, Tiger Salamander",
    prey: "Two-tailed Swallowtail, Cabbage White, Black Swallowtail, painted lady",
    fun_fact: "Funnel Web Spiders are quick to respond to vibrations in their webs, often attacking prey within seconds.",
    animal_type: "arachnid",
    diet: "Insects"
  },
  {
    name: "Deer Tick",
    scientific_name: "Ixodes scapularis",
    photo_url: "https://images.pexels.com/photos/19068832/pexels-photo-19068832.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    description: "A small tick, also known as the black-legged tick, that is a vector for Lyme disease and other illnesses.",
    top_speed: "0.003 mph",
    life_span: "2 years",
    weight: "0.002 lbs",
    height: "0.002 ft",
    length: "0.003 ft",
    habitat: "Forested areas, grassy meadows, and shrubby landscapes",
    predators: "Black-billed Magpie, raccoons, chickadees",
    prey: "blood",
    fun_fact: "Deer ticks are named for their preference to feed on deer but also target smaller mammals and humans.",
    animal_type: "arachnid",
    diet: "Blood from mammals, reptiles, and birds"
  },
  {
    name: "Crayfish",
    scientific_name: "Astacoidea",
    photo_url: "https://images.pexels.com/photos/17441481/pexels-photo-17441481.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    description: "Crayfish are freshwater crustaceans, resembling small lobsters, found in streams, rivers, and lakes. They play a vital role in the aquatic ecosystem.",
    top_speed: "0.5 mph",
    life_span: "6 years",
    weight: "0.5 lbs",
    height: "0.1 ft",
    length: "0.2 ft",
    habitat: "Freshwater environments such as streams, rivers, ponds, and lakes",
    predators: "rainbow trout, western painted turtles, raccoons",
    prey: "mayflies",
    fun_fact: "Crayfish have powerful claws that they use to defend themselves from predators and to catch prey.",
    animal_type: "Crustacean",
    diet: "Omnivore"
  }

  # Add the rest of your animals here
]

# Specify CSV file path
csv_file_path = "third_test_animals.csv"

# Write to CSV file
CSV.open(csv_file_path, "w") do |csv|
  # Add headers
  csv << ["name", "scientific_name", "photo_url", "description", "top_speed", "life_span", "weight", "height", "length", "habitat", "predators", "prey", "fun_fact", "animal_type", "diet"]

  # Add animal data
  animals.each do |animal|
    csv << [
      animal[:name],
      animal[:scientific_name],
      animal[:photo_url],
      animal[:description],
      animal[:top_speed],
      animal[:life_span],
      animal[:weight],
      animal[:height],
      animal[:length],
      animal[:habitat],
      animal[:predators],
      animal[:prey],
      animal[:fun_fact],
      animal[:animal_type],
      animal[:diet]
    ]
  end
end

puts "CSV file created at #{csv_file_path}"